[build]
  command = "pnpm run build"
  publish = "dist"
  functions = "netlify/functions"

  [[redirects]]
    from = "/*"
    to = "/index.html"
    status = 200

[build.environment]
  VITE_FIREBASE_API_KEY = "AIzaSyBqswMeVXm2kGE4QI34VVAE16fwuTOIJ5c"
  VITE_FIREBASE_AUTH_DOMAIN = "ai-ootd-web.firebaseapp.com"
  VITE_FIREBASE_PROJECT_ID = "ai-ootd-web"
  VITE_FIREBASE_STORAGE_BUCKET = "ai-ootd-web.firebasestorage.app"
  VITE_FIREBASE_MESSAGING_SENDER_ID = "639750412717"
  VITE_FIREBASE_APP_ID = "1:639750412717:web:20d1af44391f1786a76924"
  VITE_FIREBASE_MEASUREMENT_ID = "G-J00HY3RM6L"
